env:
  es6: true
extends:
  - eslint:recommended
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
overrides:
  - files: "*.js"
    env:
      node: true
  - files: "**/*.{ts,tsx}"
    extends:
      - prettier/@typescript-eslint
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:import/typescript
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      sourceType: module
    rules:
      "@typescript-eslint/explicit-module-boundary-types": off
  - files: "frontend/**/*.{ts,tsx}"
    env:
      browser: true
    extends:
      - plugin:react/recommended
    parserOptions:
      jsx: true
      # project: tsconfig.frontend.json
      useJSXTextNode: true
    rules:
      react/prop-types: off
    settings:
      react:
        version: detect
  - files: "server/**/*.{ts,tsx}"
    env:
      node: true
    # parserOptions:
    #   project: tsconfig.server.json
plugins:
  - sort-keys-fix
rules:
  import/no-extraneous-dependencies: error
  import/order:
    - error
    - alphabetize:
        order: asc
  sort-keys-fix/sort-keys-fix: error
