overrides:
  - files:
      - "*.scss"
      - "*.js"
      - "*.ts"
      - "*.tsx"
    options:
      arrowParens: always
      singleQuote: true
      trailingComma: es5
      useTabs: true
  - files:
      - "*.json"
      - "*.yml"
    options:
      tabWidth: 2
